gpio_topic:
    channel: gpio/channel
    handler:
        callback: 'gpio.topic' #related to the getName() of your topic

gpio_rpc:
    channel: rpc/{method}
    handler:
        callback: 'gpio.rpc' #related to the getName() or your RPC service
    requirements:
        method:
            pattern: "[a-z_]+"
